import { StyleSheet, Platform } from "react-native";

const BRAND_PRIMARY = "#E31837";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#F8F8F8",
    paddingTop: 40,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFF",
    paddingHorizontal: 16,
    paddingTop: Platform.OS === "ios" ? 10 : 20,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#EAEAEA",
  },
  backButton: {
    padding: 5,
    marginRight: 10,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1A1A1A",
  },
  container: {
    flex: 1,
  },
  contentPadding: {
    padding: 16,
    paddingTop: 16,
    paddingBottom: 160,
  },
  section: {
    backgroundColor: "#FFF",
    borderRadius: 8,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#EAEAEA",
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#333",
    marginBottom: 12,
  },
  subSectionTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#333",
  },
  optionsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
  },
  optionCard: {
    flex: 1,
    borderWidth: 1.5,
    borderColor: "#EAEAEA",
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 8,
    alignItems: "center",
    backgroundColor: "#FAFAFA",
  },
  optionCardActive: {
    borderColor: BRAND_PRIMARY,
    backgroundColor: "#FFF5F5",
  },
  optionText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#666",
    marginTop: 6,
  },
  optionTextActive: {
    color: BRAND_PRIMARY,
  },

  // NOVOS ESTILOS DE ENTREGA E RETIRADA
  deliveryDetailsContainer: {
    marginTop: 16,
    borderTopWidth: 1,
    borderTopColor: "#EAEAEA",
    paddingTop: 16,
  },
  storeInfoBox: {
    flexDirection: "row",
    backgroundColor: "#F5F5F5",
    padding: 12,
    borderRadius: 8,
    alignItems: "flex-start",
  },
  storeInfoTextContainer: {
    marginLeft: 10,
    flex: 1,
  },
  storeInfoTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#333",
    marginBottom: 4,
  },
  storeInfoText: {
    fontSize: 13,
    color: "#666",
    marginBottom: 2,
  },
  storeInfoHours: {
    fontSize: 12,
    color: "#666",
    marginTop: 6,
    fontWeight: "500",
  },
  addressHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  emptyAddressText: {
    fontSize: 14,
    color: "#999",
    fontStyle: "italic",
    textAlign: "center",
    marginTop: 10,
  },
  addressItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: "#EAEAEA",
    borderRadius: 8,
    marginBottom: 8,
  },
  addressItemActive: {
    borderColor: BRAND_PRIMARY,
    backgroundColor: "#FFF5F5",
  },
  addressItemTextContainer: {
    marginLeft: 12,
    flex: 1,
  },
  addressItemStreet: {
    fontSize: 14,
    fontWeight: "600",
    color: "#333",
  },
  addressItemDetails: {
    fontSize: 12,
    color: "#666",
    marginTop: 2,
  },
  defaultBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFF5F5",
    borderWidth: 1,
    borderColor: "rgba(227, 24, 55, 0.3)", 
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    marginLeft: 8,
  },
  defaultBadgeText: {
    fontSize: 10,
    color: "#E31837",
    fontWeight: "700",
    marginLeft: 2,
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  summaryLabel: {
    fontSize: 14,
    color: "#666",
  },
  summaryValue: {
    fontSize: 14,
    color: "#333",
    fontWeight: "500",
  },
  summaryTotalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: "#EAEAEA",
  },
  summaryTotalLabel: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1A1A1A",
  },
  summaryTotalValue: {
    fontSize: 18,
    fontWeight: "700",
    color: BRAND_PRIMARY,
  },
  footer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#FFF",
    padding: 16,
    paddingBottom: Platform.OS === "ios" ? 30 : 16,
    borderTopWidth: 1,
    borderTopColor: "#EAEAEA",
    elevation: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
  },
  confirmButton: {
    backgroundColor: BRAND_PRIMARY,
    height: 50,
    borderRadius: 6,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
  },
  confirmButtonText: {
    color: "#FFF",
    fontSize: 16,
    fontWeight: "700",
  },
  continueShoppingButton: {
    alignItems: "center",
    paddingVertical: 5,
  },
  continueShoppingText: {
    color: "#666",
    fontSize: 14,
    fontWeight: "500",
  },
});
